import next from "next"
import "./styles.css"

import {Metadata} from "next"

export const metadata:Metadata = {
  title: {
    absolute:"",
    default:"default title for child route.",
    template:"template title | %s"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="p-4 bg-slate-500 ">Header</header>
        <main>{children}</main>
        <footer className="p-4 bg-green-400">Footer</footer>
        
        </body>
    </html>
  )
}
